services:
    messageboard.guestLanguage.listener:
        class: messageboard\guestLanguage\event\main_listener
        arguments:
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }